import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import { useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[query, getQuery]=useState();
  const router = useRouter();
  const handleOnChange = e => getQuery(e.target.value)
  const handleOnSubmit = e => {
    e.preventDefault()
    router.push(`/news/${query}`)
  }

  return (
    <Layout>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1 className={styles.title}>News fEED</h1>

       <form onSubmit={handleOnSubmit}>
        <input type="text" onChange={handleOnChange}/>
       </form>

       <div className={styles.grid}>
        <Link href="/news/" className = {styles.card}>
          <h2>Top Stories</h2>
        </Link>

       </div>

        <div className={styles.grid}>
          <Link href="/learn/next"
            className={styles.card}
          >
            <h2>
              Learn next
            </h2>
          </Link>

          <Link href="/learn/react"
            className={styles.card}
          >
            <h2>
              Learn react
            </h2>
          </Link>

          <Link href="/learn/vue"
            className={styles.card}
          >
            <h2>
              Learn vue
            </h2>
          </Link>

          <Link href="/learn/angular"
            className={styles.card}
          >
            <h2>
              Learn angular
            </h2>
          </Link>
          <Link href="/news/"
            className={styles.card}
          >
            <h2>
              Top stories
            </h2>

          </Link>



        </div>

      </main>
    </Layout>
  )
}
